# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image-Magick-Thumbnail
version:      0.02
version_from: Thumbnail.pm
installdirs:  site
requires:
    Image::Magick:                 0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
